name: Python CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  python-ci:

    runs-on: ubuntu-latest

    steps:

      # 1. Download source code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Python program
      - name: Run Python program
        run: |
          python main.py

      # 5. Run automated tests
      - name: Run tests
        run: |
          pytest -v

      # 6. Verify generated output file
      - name: Verify output file
        run: |
          test -f output/employee_salary_report.csv
          echo "Output file exists"
          echo "Output file contents:"
          cat output/employee_salary_report.csv